---
- name: Delete existing installation of golang
  file:
    path: /usr/local/go
    state: absent

- name: Download golang
  get_url:
    url: "https://golang.org/dl/{{ golang_version }}.linux-amd64.tar.gz"
    dest: "/usr/src/{{ golang_version }}.linux-amd64.tar.gz"
    mode: "0644"

- name: Unpack golang
  unarchive:
    src: "/usr/src/{{ golang_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes

- name: Copy go.sh
  copy:
    src: "{{ role_path }}/files/go.sh"
    dest: /etc/profile.d/go.sh
    mode: "0755"

- name: Set GOPATH
  become_user: "{{ user }}"
  lineinfile:
    dest: ~/.profile
    state: present
    line: "export GOPATH=/home/{{ user }}/go"

- name: Set GOBIN
  become_user: "{{ user }}"
  lineinfile:
    dest: ~/.profile
    state: present
    line: "export GOBIN=$GOPATH/bin"

- name: Update PATH
  become_user: "{{ user }}"
  lineinfile:
    dest: ~/.profile
    state: present
    line: "export PATH=$PATH:$GOBIN"
